# -*- coding: utf-8 -*-
"""Event class

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hn0tW9hIoWs8J8ZyR0SQfDLcOUs5Pt0b
"""

class Event:
    def __init__(self, name, location, duration, price):
        self.name = name
        self.location = location
        self.duration = duration
        self.price = price

    # Getter and setter methods for name
    def get_name(self):
        return self.name

    def set_name(self, name):
        self.name = name

    # Getter and setter methods for location
    def get_location(self):
        return self.location

    def set_location(self, location):
        self.location = location

    # Getter and setter methods for duration
    def get_duration(self):
        return self.duration

    def set_duration(self, duration):
        self.duration = duration

    # Getter and setter methods for price
    def get_price(self):
        return self.price

    def set_price(self, price):
        self.price = price