# -*- coding: utf-8 -*-
"""Exhibition Class

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L4bsX55fWwf6c4a-V-5XxBRqVGo-0JbF
"""

class Exhibition:
    def __init__(self, location, duration):
        self.location = location
        self.duration = duration
        self.artworks = []

    # Getter and setter methods for location
    def get_location(self):
        return self.location

    def set_location(self, location):
        self.location = location

    # Getter and setter methods for duration
    def get_duration(self):
        return self.duration

    def set_duration(self, duration):
        self.duration = duration

    # Getter and setter methods for artworks
    def get_artworks(self):
        return self.artworks

    def add_artwork(self, artwork):
        self.artworks.append(artwork)