# -*- coding: utf-8 -*-
"""Ticket class

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Qy-Q1J0I_gTA9Gqon_S9KzaKDnYpF1e
"""

class Ticket:
    def __init__(self, price, visitor, exhibition=None, event=None, tour_date=None, event_date=None, group_size=0,
                 is_group=False, is_special_event=False, is_tour=False):
        self.price = price
        self.visitor = visitor
        self.exhibition = exhibition
        self.event = event
        self.tour_date = tour_date
        self.event_date = event_date
        self.group_size = group_size
        self.is_group = is_group
        self.is_special_event = is_special_event
        self.is_tour = is_tour

    # Getter and setter methods for price
    def get_price(self):
        return self.price

    def set_price(self, price):
        self.price = price

    # Getter and setter methods for visitor
    def get_visitor(self):
        return self.visitor

    def set_visitor(self, visitor):
        self.visitor = visitor

    # Getter and setter methods for exhibition
    def get_exhibition(self):
        return self.exhibition

    def set_exhibition(self, exhibition):
        self.exhibition = exhibition

    # Getter and setter methods for event
    def get_event(self):
        return self.event

    def set_event(self, event):
        self.event = event

    # Getter and setter methods for tour_date
    def get_tour_date(self):
        return self.tour_date

    def set_tour_date(self, tour_date):
        self.tour_date = tour_date

    # Getter and setter methods for event_date
    def get_event_date(self):
        return self.event_date

    def set_event_date(self, event_date):
        self.event_date = event_date

    # Getter and setter methods for group_size
    def get_group_size(self):
        return self.group_size

    def set_group_size(self, group_size):
        self.group_size = group_size

    # Getter and setter methods for is_group
    def get_is_group(self):
        return self.is_group

    def set_is_group(self, is_group):
        self.is_group = is_group

    # Getter and setter methods for is_special_event
    def get_is_special_event(self):
        return self.is_special_event

    def set_is_special_event(self, is_special_event):
        self.is_special_event = is_special_event

    # Getter and setter methods for is_tour
    def get_is_tour(self):
        return self.is_tour

    def set_is_tour(self, is_tour):
        self.is_tour = is_tour